### ISSUE TITLE
Issues with running backend services

### ISSUE THREAD

**Issue by myanzik** [unicef/hope#4250]
I tried to run the project locally following the [development setup documentation](https://github.com/unicef/hope/blob/master/docs/technical-specification/development-setup/README.md). However, I encountered an error while executing the command:

```bash
docker exec -it <prefix>_backend_1 ./manage.py initdemo
```

I used `hct-mis` as the prefix, so my command looked like this:

```bash
docker exec -it hct-mis-backend-1 ./manage.py initdemo
```

But I received the following error on the `hct-mis-backend-1` container:

**Error Log**:
```
2024-09-19 20:36:06 db:5432 - accepting connections
2024-09-19 20:36:08 Traceback (most recent call last):
2024-09-19 20:36:08   File "/code/manage.py", line 10, in <module>
2024-09-19 20:36:08     execute_from_command_line(sys.argv)
2024-09-19 20:36:08   File "/packages/__pypackages__/3.11/lib/django/core/management/__init__.py", line 419, in execute_from_command_line
2024-09-19 20:36:08     utility.execute()
2024-09-19 20:36:08   File "/packages/__pypackages__/3.11/lib/django/core/management/__init__.py", line 363, in execute
2024-09-19 20:36:08     settings.INSTALLED_APPS
2024-09-19 20:36:08   File "/packages/__pypackages__/3.11/lib/django/conf/__init__.py", line 82, in __getattr__
2024-09-19 20:36:08     self._setup(name)
2024-09-19 20:36:08   File "/packages/__pypackages__/3.11/lib/django/conf/__init__.py", line 69, in _setup
2024-09-19 20:36:08     self._wrapped = Settings(settings_module)
2024-09-19 20:36:08                     ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:36:08   File "/packages/__pypackages__/3.11/lib/django/conf/__init__.py", line 170, in __init__
2024-09-19 20:36:08     mod = importlib.import_module(self.SETTINGS_MODULE)
2024-09-19 20:36:08           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:36:08   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
2024-09-19 20:36:08     return _bootstrap._gcd_import(name[level:], package, level)
2024-09-19 20:36:08            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:36:08   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-09-19 20:36:08   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-09-19 20:36:08   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-09-19 20:36:08   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-09-19 20:36:08   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-09-19 20:36:08   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-09-19 20:36:08   File "/code/hct_mis_api/config/settings.py", line 534, in <module>
2024-09-19 20:36:08     from hct_mis_api.config.fragments.csp import *  # noqa: F403, F401, E402
2024-09-19 20:36:08     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:36:08   File "/code/hct_mis_api/config/fragments/csp.py", line 8, in <module>
2024-09-19 20:36:08     CSP_REPORT_PERCENTAGE = env("CSP_REPORT_PERCENTAGE")
2024-09-19 20:36:08                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:36:08   File "/packages/__pypackages__/3.11/lib/environ/environ.py", line 199, in __call__
2024-09-19 20:36:08     return self.get_value(
2024-09-19 20:36:08            ^^^^^^^^^^^^^^^
2024-09-19 20:36:08   File "/packages/__pypackages__/3.11/lib/environ/environ.py", line 415, in get_value
2024-09-19 20:36:08     value = self.parse_value(value, cast)
2024-09-19 20:36:08             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-19 20:36:08   File "/packages/__pypackages__/3.11/lib/environ/environ.py", line 472, in parse_value
2024-09-19 20:36:08     value = float(float_str)
2024-09-19 20:36:08             ^^^^^^^^^^^^^^^^
2024-09-19 20:36:08 ValueError: could not convert string to float: ''
```

**Steps to Reproduce**:
1. Follow the [development setup documentation](https://github.com/unicef/hope/blob/master/docs/technical-specification/development-setup/README.md)
2. Run the command `docker exec -it hct-mis-backend-1 ./manage.py initdemo`

Can anybody guide me on this?

**Comment by ntrncic** [comment]
We have updated our documentation, please refer to the new one here https://unicef.github.io/hope-documentation/guide-dev/setup/. With this you should be able to setup HOPE locally.
